/**
 * This file was auto-generated by the Titanium Module SDK helper for Android
 * Appcelerator Titanium Mobile
 * Copyright (c) 2009-2010 by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 *
 */
package com.pushbots.android;

import org.appcelerator.kroll.KrollModule;
import org.appcelerator.kroll.annotations.Kroll;
import org.appcelerator.titanium.TiApplication;
import org.appcelerator.kroll.common.Log;
import org.appcelerator.kroll.common.TiConfig;

import com.pushbots.push.Pushbots;

@Kroll.module(name = "Pushbots", id = "com.pushbots.android")
public class PushbotsModule extends KrollModule {

	// Standard Debugging variables
	private static final String LCAT = "PushbotsModule";
	private static final boolean DBG = TiConfig.LOGD;

	public static TiApplication app;
	private Pushbots pushbots;

	// You can define constants with @Kroll.constant, for example:
	// @Kroll.constant public static final String EXTERNAL_NAME = value;

	public PushbotsModule() {
		super();
	}

	@Kroll.onAppCreate
	public static void onAppCreate(TiApplication app) {
		Log.d(LCAT, "inside onAppCreate");
		// put module init code that needs to run when the application is
		// created
		PushbotsModule.app = app;
		Pushbots.sharedInstance().init(app);
		
		Log.d(LCAT, "Pushbots intitalized");
	}
	
	// Methods
	@Kroll.method
	public void tag(String tag, String alias) {
		Log.d(LCAT, "setting Pushbots tag, " + tag + ", " + alias);
		Pushbots.sharedInstance().tag(PushbotsModule.app, tag, alias);
	}

	// Properties
	@Kroll.setProperty
	public void setAlias(String alias) {
		Log.d(LCAT, "setting Pushbots alias");
		Pushbots.sharedInstance().setAlias(app, alias);
	}

	@Kroll.getProperty
	public Boolean getEnabled() {
		Log.d(LCAT, "getting Pushbots notification enabled");
		return Pushbots.sharedInstance().isPushEnabled();
	}

	@Kroll.setProperty
	public void setEnabled(Boolean enabled) {
		Log.d(LCAT, "setting Pushbots notification enabled to true");
		Pushbots.sharedInstance().setPushEnabled(enabled);
	}

}
